apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJtZHZZMmgxZVdzNE9qQXlNREpJZFhreU1EQXlRQT09IgoJCX0KCX0KfQ==root@vps-102:~/.docker#